Improve error message when network results do not exist (#182)
Consider this example
```python
import roseau.load_flow as lf
en = lf.ElectricalNetwork.from_catalogue("LVFeeder00939", "summer")
en.res_loads  # <- error
```

Before:
```
RoseauLoadFlowException: Results for PowerLoad 'LVBus004111_production' are not available because the load flow has not been run yet. [load_flow_not_run]
```

After:
```
RoseauLoadFlowException: The load flow results are not available because the load flow has not been run yet. [load_flow_not_run]
```